# Generated by Django 4.1.1 on 2022-10-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_size_price_size_price_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='unit',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
